import "./globals.css"; // Change from ../ to ./
import React from "react"; // This fixes the red "React" error

export const metadata = {
  title: "AI Background Remover",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}